name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies (no lock file check)
      run: npm install --no-package-lock

    - name: Build
      run: npm run build --if-present

    - name: Run tests
      run: npm test --if-present
